plugin {
    hymission {
      gesture = 3, vertical, dispatcher, hymission:toggle,forceall
      gesture = 3, vertical, dispatcher, hymission:toggle,recommand
      gesture = 3, vertical, dispatcher, hymission:open,onlycurrentworkspace
    }
}

