-- Auto-generated by HyDE // Read-only
-- // ----------------------------
-- HyDE Theme: Catppuccin Mocha
-- Configuration File: "/home/khing/.config/hyde/themes/Catppuccin Mocha/hypr.theme"
-- Wallbash Mode : theme
-- // ----------------------------

HYDE_THEME = "Catppuccin Mocha"
GTK_THEME = "Catppuccin-Mocha"
COLOR_SCHEME = "prefer-dark"

CODE_THEME = "Wallbash"
SDDM_THEME = ""
